"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ulh9caf*uum&oa2#6gwg*aw4p4@%6mt+k5ufa4-&2tz-n^szev'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'blog.apps.BlogConfig',
    'users.apps.UsersConfig',
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

#Changing the default directory of where media is saved
MEDIA_ROOT=os.path.join(BASE_DIR,"media")

#Where media can be accessed through the browser
MEDIA_URL="/media/" 

#Setting what version of Bootstrap to be used when Crispy template is loaded.
CRISPY_TEMPLATE_PACK ='bootstrap4'

#Changing the default refirect URL when...? (Confirm)
LOGIN_REDIRECT_URL = 'blog-home'

#Setting where decorator routes when page is opened by inauthenticated user.
LOGIN_URL = 'login'

#Email settings to enable password reset
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST = "smtp.office365.com"
EMAIL_PORT = 587
# EMAIL_PORT = 25
EMAIL_USE_TLS = True

#Passing in email credentials via environment variables
# DEFAULT_FROM_EMAIL = os.environ.get("GMAIL_USERNAME")
# EMAIL_FROM = os.environ.get("GMAIL_USERNAME")
# EMIL_HOST_USER = os.environ.get("GMAIL_USERNAME")
# EMAIL_HOST_PASSWORD = os.environ.get("GMAIL_APP_PASSWORD")

DEFAULT_FROM_EMAIL = os.environ.get("OUTLOOK_USERNAME")
# EMAIL_FROM = os.environ.get("OUTLOOK_USERNAME")
EMAIL_HOST_USER =os.environ.get("OUTLOOK_USERNAME")
EMAIL_HOST_PASSWORD = os.environ.get("OUTLOOK_PASSWORD")