# Generated by Django 3.0 on 2020-04-16 15:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200413_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Upload_file',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='default.jpg'),
        ),
    ]
