# Generated by Django 3.0 on 2020-04-16 15:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Upload_file',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
